{% set name = "lava-dl" %}
{% set version = "0.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lava-nc/lava-dl/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c4e00edc186ff0e9f53195f38a108d2273a1fd8bcf5b65ff0bb2f5ffddf9e6eb
  patches:
    - fix-setup-py.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    # only required to get the version from build.py
    - pybuilder
  run:
    - python >=3.6
    - matplotlib-base
    - numpy
    - lava
    - pytorch
    - torchvision
    - scipy
    - ninja
    - h5py

test:
  imports:
    - lava.lib.dl.slayer
    - lava.lib.dl.bootstrap

about:
  home: https://github.com/lava-nc/lava-dl
  summary: lava-dl is a library of deep learning tools within Lava that support offline training, online training and inference methods for various Deep Event-Based Networks.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
