{% set name = "lava-dl" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lava-nc/lava-dl/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e7306803fac771a8175ecad1160334c50a5d129d89063f818fb797b9c5cdcbdc
  patches:
    - fix-unnecessary-import.patch

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - poetry-core
  run:
    - python
    - matplotlib-base
    - numpy
    - lava
    - pytorch
    - torchvision  # [not win]
    - scipy
    - ninja
    - h5py
    - setuptools

test:
  requires:
    - pytest
  source_files:
    - tests
  imports:
    - lava.lib.dl.slayer
    - lava.lib.dl.bootstrap
    - lava.lib.dl.netx
  commands:
    - pytest

about:
  home: https://github.com/lava-nc/lava-dl
  summary: lava-dl is a library of deep learning tools within Lava that support offline training, online training and inference methods for various Deep Event-Based Networks.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
